version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.8.1-browsers
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: tuck-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: tuck-{{ checksum "project.clj" }}
      - run: lein test
